[2023-09-09 13:35:49]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=855610826&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000214B9C2AF90>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-09 13:35:54]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=855610826&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000214B8679E50>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-09 13:35:58]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=855610826&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000214B869C9D0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-09 13:36:02]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=855610826&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000214B8678410>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
