[2023-09-12 18:29:25]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002860EE1AB90>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 18:29:41]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028611E68850>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 18:29:57]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028611E9A690>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 18:30:13]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028611E69290>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 18:35:32]: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
[2023-09-12 18:35:48]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028611F193D0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 18:36:04]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028611EED250>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 18:36:20]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028611F19D50>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 18:36:33]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028611E69B90>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 18:36:37]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028611E54150>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 18:36:53]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028611E9A550>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 18:48:45]: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
[2023-09-12 18:49:01]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028611E57190>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 18:49:05]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028610EACF10>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 18:49:09]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028611EEE6D0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 18:49:25]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028611F19290>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 18:49:42]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028611EEE890>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 18:49:54]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028610EAD350>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 18:49:58]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028611F191D0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 18:50:14]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028611F18690>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 18:50:18]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028610EAD0D0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 18:50:22]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028611E9AB50>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 18:50:26]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028611E57A50>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 18:50:30]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028610EAD890>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 18:50:46]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028610D91390>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 18:50:50]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028611E3E850>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 18:51:06]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028611117D90>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 18:51:10]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028611E3EED0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 18:51:14]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028611E5D690>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 18:51:18]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028610EADA90>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 18:51:22]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002860E9E0390>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 18:51:26]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002860F047E90>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 18:51:30]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028611EEF250>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 18:51:34]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028611E99B50>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 18:51:38]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002860F044E50>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 18:51:42]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028610EAD390>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 18:51:46]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028611E5DE90>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 18:51:50]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002860F042050>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 18:51:54]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028611EEF350>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 18:51:58]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028611E9B090>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 18:52:02]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002860F01CE10>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 18:57:33]: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
[2023-09-12 18:57:49]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028610FF0210>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 18:57:53]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002860F01FBD0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 18:58:05]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028611EEFFD0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 18:58:21]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028611E990D0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 18:58:25]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002860F00E8D0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 18:58:29]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002860E9D28D0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 18:58:33]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028611F19DD0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 18:58:49]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002860F075610>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 18:58:56]: ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
[2023-09-12 18:59:00]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002860F01DB10>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 19:10:13]: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
[2023-09-12 19:10:29]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002860F01D990>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 19:10:33]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002860F00C650>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 19:10:37]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002860F043410>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 19:10:41]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002860F00DE50>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 19:10:45]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002860F01FDD0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 19:11:01]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002860F045D50>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 19:11:05]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002860F047C50>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 19:11:09]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002860F042B50>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 19:11:25]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002860F949610>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 19:11:29]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028611E5D2D0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 19:11:33]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002860F041090>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 19:11:49]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028611E5D1D0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 19:12:06]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028611E3D490>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 19:18:17]: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
[2023-09-12 19:18:33]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002860F041450>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 19:18:49]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028611E3F4D0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 19:19:05]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028611E3E190>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 19:19:09]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002860F047610>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 19:19:13]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028611E55310>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 19:19:17]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028611E98D90>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 19:19:33]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002860F00D790>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 19:19:49]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002860F043610>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 19:19:53]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002860FA94C90>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
[2023-09-12 20:18:30]: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028611E69190>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
