2023-09-05 13:31:22: list index out of range
2023-09-05 13:32:12: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000282648C4E50>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 13:32:48: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2023-09-05 13:43:08: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2023-09-05 13:45:16: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2023-09-05 13:47:39: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2023-09-05 13:48:40: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F72AC01290>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 13:48:50: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F72AC91AD0>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 13:49:00: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F72AC87610>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 13:49:36: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2023-09-05 13:51:32: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000020A21197990>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 13:55:02: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2023-09-05 13:55:12: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FCD18E2E90>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 13:55:22: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FCD18FCA10>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 14:00:34: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2023-09-05 14:00:44: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000216852F7890>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 14:00:54: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021685301890>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 14:01:04: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021686069F50>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 14:01:14: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021687D71CD0>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 14:01:24: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021687D73A90>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 14:01:57: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000021685287350>, 'Connection to www.google.com timed out. (connect timeout=None)'))
2023-09-05 14:02:07: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021686069E10>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 14:02:17: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021685301A10>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 14:02:48: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000021687D739D0>, 'Connection to www.google.com timed out. (connect timeout=None)'))
2023-09-05 14:02:58: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021687D71950>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 14:03:09: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000216877D4B50>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 14:03:19: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000216852F6F50>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 14:03:29: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000216864061D0>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 14:03:39: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021685301710>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 14:03:49: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021687D73310>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 14:04:08: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021687D72B10>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 14:04:18: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000216877D4190>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 14:04:28: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021687D95450>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 14:04:38: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021686069ED0>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 14:04:48: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021685300D50>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 14:05:10: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021687D73890>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 14:05:31: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021687D73410>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 14:05:41: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000216877D4290>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 14:05:51: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021687D97690>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 14:06:01: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021686406290>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 14:06:11: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021687D725D0>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 14:06:21: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021687D72CD0>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 14:06:31: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021685301150>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 14:06:41: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002168606A550>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 14:06:51: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002168253E590>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 14:07:01: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021687D947D0>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 14:07:11: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021685300D90>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 14:07:21: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000216860698D0>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 14:07:31: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021687D73DD0>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 14:07:41: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000216852E6410>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 14:07:51: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000216864063D0>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 14:08:01: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021687D97250>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 14:08:11: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021687D72FD0>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 14:08:21: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021687D71610>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 14:08:31: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000216851E4090>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 14:08:41: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021685300B90>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 14:08:51: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002168606A2D0>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 14:09:01: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000216877D4890>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 14:09:11: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002168606ABD0>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 14:09:21: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000216852E4350>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 14:09:31: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021685300F90>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 14:09:41: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000216852F7190>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 14:09:51: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021687D73750>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 14:10:01: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021687D71B10>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 14:10:15: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021687D94190>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 14:31:16: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2023-09-05 14:43:12: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2023-09-05 17:25:02: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2023-09-05 17:25:14: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002536CA79B10>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 17:25:26: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002536CA88FD0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 17:25:43: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002536A11FC50>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 17:27:20: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2023-09-05 17:27:32: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=855610657&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002536A30B5D0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 17:27:48: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=855610657&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002536D56B510>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 17:29:25: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2023-09-05 17:29:37: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=855610657&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002536D56ABD0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 17:29:49: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=855610657&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002536B0B4F50>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 17:30:03: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=855610657&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002536ADE2E50>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 17:32:21: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2023-09-05 17:32:33: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=855610657&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002536D012490>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 17:32:45: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=855610657&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002536CFED290>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 17:32:57: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=855610657&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002536D01CC10>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 17:33:13: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=855610657&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002536D013ED0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 17:33:25: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=855610657&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002536D01EBD0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 17:33:37: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=855610657&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002536B389010>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 17:33:49: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=855610657&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002536B541F90>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 17:34:51: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2023-09-05 17:35:03: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=855610657&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002536B2128D0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 17:35:15: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=855610657&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002536B1B2350>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 17:37:55: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2023-09-05 17:39:53: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2023-09-05 17:41:04: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2023-09-05 17:46:21: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2023-09-05 20:36:48: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2023-09-05 20:42:27: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2023-09-05 20:42:41: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=855610663&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001D993080550>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 20:42:53: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=855610663&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001D993082F50>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 20:43:09: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=855610663&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001D99356E590>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 20:43:21: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=855610663&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001D993B73090>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 20:44:39: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2023-09-05 20:44:51: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=855610663&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001D9915CE950>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 20:45:03: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=855610663&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001D99414A3D0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 20:45:17: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=855610663&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001D993728210>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 20:45:29: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=855610663&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001D99356E090>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 20:45:45: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=855610663&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001D99379AE10>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 20:45:57: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=855610663&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001D993764310>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 20:59:35: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2023-09-05 21:08:47: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2023-09-05 21:10:54: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2023-09-05 21:12:43: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2023-09-05 21:17:32: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2023-09-05 21:17:44: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000020D3B776A50>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 21:18:50: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2023-09-05 21:25:39: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2023-09-05 21:25:51: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000172F8E8B1D0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 21:28:15: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2023-09-05 21:28:27: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=855610688&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022F9B1C4D50>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 21:31:29: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2023-09-05 21:38:31: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2023-09-06 08:21:16: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
