2023-09-05 11:21:14: cannot access local variable 'e' where it is not associated with a value2023-09-05 11:21:24: cannot access local variable 'e' where it is not associated with a value2023-09-05 11:21:34: cannot access local variable 'e' where it is not associated with a value2023-09-05 11:21:44: cannot access local variable 'e' where it is not associated with a value2023-09-05 11:21:59: cannot access local variable 'e' where it is not associated with a value2023-09-05 11:22:09: cannot access local variable 'e' where it is not associated with a value2023-09-05 11:22:19: cannot access local variable 'e' where it is not associated with a value2023-09-05 11:23:56: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001C3331ACE90>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))2023-09-05 11:24:06: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001C333C89C50>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))2023-09-05 11:24:16: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001C333C7C410>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))2023-09-05 11:24:29: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000023E868F83D0>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 11:24:39: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000023E873B9E90>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 11:24:49: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000023E873ACA10>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 11:24:59: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000023E873BADD0>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 11:25:20: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000023E873CC510>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 11:25:30: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000023E873CDF10>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 11:25:49: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000023E873CF910>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 11:25:59: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000023E873D9350>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 11:26:16: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000023E873CEB50>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 11:26:26: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000023E873CCA50>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 11:30:42: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=60)
2023-09-05 11:30:52: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021771373E10>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 11:31:02: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021771370910>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 11:31:12: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021771371190>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 11:31:22: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021771370450>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 11:31:32: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002176F239C10>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 11:31:42: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021771353550>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 11:31:52: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002176F590190>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 11:32:02: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002176F593810>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 11:32:12: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002176F590390>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 11:34:59: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000021771A50910>, 'Connection to www.google.com timed out. (connect timeout=None)'))
2023-09-05 11:35:30: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000021771A52250>, 'Connection to www.google.com timed out. (connect timeout=None)'))
2023-09-05 11:36:01: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000021771A53B10>, 'Connection to www.google.com timed out. (connect timeout=None)'))
2023-09-05 11:36:32: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000021771A66890>, 'Connection to www.google.com timed out. (connect timeout=None)'))
2023-09-05 11:43:35: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2023-09-05 11:43:45: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000234ED09DF10>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 11:43:55: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000234ED0A5450>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 11:44:05: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000234ED09F0D0>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 11:44:15: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000234ED084310>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 11:44:36: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000177B54A4E90>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 11:44:46: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000177B5689E50>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 11:44:56: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000177B567C610>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 11:45:06: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000177B568ADD0>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 11:45:16: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000177B569C4D0>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 11:45:26: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000177B569DF10>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 11:45:36: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000177B569F950>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 11:45:46: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000177B56A93D0>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 11:45:56: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000177B569EBD0>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 11:46:06: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000177B569CF50>: Failed to resolve 'www.google.com' ([Errno 11001] getaddrinfo failed)"))
2023-09-05 11:54:20: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
