2023-09-07 16:05:52: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2023-09-07 16:06:04: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000010D24067CD0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 16:06:16: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000010D24086650>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 16:06:28: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000010D24086750>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 16:06:40: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000010D24067C10>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 16:06:52: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000010D24095990>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 16:07:04: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000010D24094610>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 16:07:16: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000010D24067590>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 16:07:28: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000010D2409CBD0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 16:07:40: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000010D2409F950>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 16:07:52: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000010D240667D0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 16:08:04: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000010D2409FED0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 16:08:16: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000010D240AE990>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 16:08:28: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000010D24067010>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 16:08:40: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000010D240AC050>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 16:08:52: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000010D240C1B10>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 16:09:04: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000010D24095F90>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 16:09:16: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000010D240678D0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 16:09:28: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000010D240CCCD0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 16:09:40: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000010D24067490>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 16:09:52: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000010D24085010>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 16:10:04: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000010D240CFD50>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 16:10:16: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000010D240C3ED0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 16:10:28: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000010D240C1310>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 16:10:40: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000010D240AD590>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 16:10:53: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000010D240C2D50>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 16:11:05: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000010D240CD0D0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 16:11:17: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000010D240AD810>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 16:11:29: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000010D240AC250>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 16:11:41: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000010D240C2E10>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 16:11:53: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000010D2409DDD0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 16:12:05: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000010D24066750>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 16:12:17: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000010D240CD0D0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 16:12:29: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000010D240AEE90>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 16:12:41: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000010D24097010>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 16:16:35: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2023-09-07 16:17:33: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2023-09-07 16:17:45: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000181E5392CD0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 16:19:41: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2023-09-07 16:19:53: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001BD8B919A10>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 16:20:07: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001BD8B928A50>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 16:20:19: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001BD8B918D10>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 16:20:31: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001BD8B8FA590>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 16:20:43: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001BD8B92AF50>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 16:23:42: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2023-09-07 16:23:54: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000023532699410>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 16:24:08: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000023534255AD0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 16:24:20: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000023531C0C510>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 16:28:49: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2023-09-07 16:29:01: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001DB25C7F190>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 16:29:15: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001DB25C9DC90>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 16:35:17: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getMe (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001C84124B850>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 16:35:29: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getMe (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001C84085F950>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 16:42:16: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2023-09-07 16:42:28: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028AD0597790>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 16:42:40: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028ACD6623D0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 16:42:52: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028ACFFCB350>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 17:04:04: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2023-09-07 17:04:16: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002157C596D90>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 17:04:28: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002157A511A90>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 17:40:12: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2023-09-07 17:40:31: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getMe (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001A81F6B46D0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 17:40:43: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getMe (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001A82016FC10>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 17:40:55: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getMe (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001A820174C10>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-07 17:41:07: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getMe (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001A82016EF50>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-08 14:30:05: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2023-09-08 14:32:26: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getMe (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001732DEBAD90>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-08 14:33:58: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getMe (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000165175DED10>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-08 14:34:46: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2023-09-08 14:34:59: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=855610759&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000165177A0C10>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-08 14:35:12: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=855610759&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016517773B10>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-08 14:49:37: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getMe (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001827F86B750>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-08 14:49:51: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getMe (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001827F874A90>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-08 14:50:05: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getMe (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001827F875CD0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-08 14:56:39: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2023-09-08 14:56:53: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001B523D3E650>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-08 14:57:07: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001B523C34650>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-08 15:01:32: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2023-09-08 15:01:46: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000015FBF9B3F10>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-08 15:02:00: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000015FBF9B61D0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-08 15:02:14: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000015FBF9CE910>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-08 15:05:37: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2023-09-08 15:06:27: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getMe (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000019482EC5790>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-08 15:06:41: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getMe (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000019482ED86D0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-08 15:06:55: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getMe (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000019482EDB390>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-08 15:07:34: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2023-09-08 15:07:48: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000194833D5B90>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-08 15:08:02: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000194833D6350>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-08 15:10:31: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2023-09-08 15:10:45: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002540F444110>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-08 15:10:59: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002540F4447D0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-08 15:11:13: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002540F45CC10>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-08 15:11:27: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002540F4437D0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-08 15:16:37: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2023-09-08 15:19:32: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2023-09-08 15:20:05: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2023-09-08 15:20:19: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/sendMessage?chat_id=533286897&text=%E2%9D%97%EF%B8%8F+%D0%92%D0%BE%D0%B7%D0%BD%D0%B8%D0%BA%D0%BB%D0%B0+%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D0%B0.%0A%0A+%EF%B8%8F%E2%9D%97%EF%B8%8F+2023-09-08+15%3A20%3A05%3A+%28%27Connection+aborted.%27%2C+RemoteDisconnected%28%27Remote+end+closed+connection+without+response%27%29%29%0A (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000237ABC0DB90>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-08 15:20:33: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/sendMessage?chat_id=533286897&text=%E2%9D%97%EF%B8%8F+%D0%92%D0%BE%D0%B7%D0%BD%D0%B8%D0%BA%D0%BB%D0%B0+%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D0%B0.%0A%0A+%EF%B8%8F%E2%9D%97%EF%B8%8F+2023-09-08+15%3A20%3A19%3A+HTTPSConnectionPool%28host%3D%27api.telegram.org%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fbot6544001225%3AAAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI%2FsendMessage%3Fchat_id%3D533286897%26text%3D%25E2%259D%2597%25EF%25B8%258F%2B%25D0%2592%25D0%25BE%25D0%25B7%25D0%25BD%25D0%25B8%25D0%25BA%25D0%25BB%25D0%25B0%2B%25D0%25BE%25D1%2588%25D0%25B8%25D0%25B1%25D0%25BA%25D0%25B0.%250A%250A%2B%25EF%25B8%258F%25E2%259D%2597%25EF%25B8%258F%2B2023-09-08%2B15%253A20%253A05%253A%2B%2528%2527Connection%2Baborted.%2527%252C%2BRemoteDisconnected%2528%2527Remote%2Bend%2Bclosed%2Bconnection%2Bwithout%2Bresponse%2527%2529%2529%250A+%28Caused+by+NameResolutionError%28%22%3Curllib3.connection.HTTPSConnection+object+at+0x00000237ABC0DB90%3E%3A+Failed+to+resolve+%27api.telegram.org%27+%28%5BErrno+11001%5D+getaddrinfo+failed%29%22%29%29%0A (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000237ABBF2510>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-08 15:20:48: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/sendMessage?chat_id=533286897&text=%E2%9D%97%EF%B8%8F+%D0%92%D0%BE%D0%B7%D0%BD%D0%B8%D0%BA%D0%BB%D0%B0+%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D0%B0.%0A%0A+%EF%B8%8F%E2%9D%97%EF%B8%8F+2023-09-08+15%3A20%3A33%3A+HTTPSConnectionPool%28host%3D%27api.telegram.org%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fbot6544001225%3AAAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI%2FsendMessage%3Fchat_id%3D533286897%26text%3D%25E2%259D%2597%25EF%25B8%258F%2B%25D0%2592%25D0%25BE%25D0%25B7%25D0%25BD%25D0%25B8%25D0%25BA%25D0%25BB%25D0%25B0%2B%25D0%25BE%25D1%2588%25D0%25B8%25D0%25B1%25D0%25BA%25D0%25B0.%250A%250A%2B%25EF%25B8%258F%25E2%259D%2597%25EF%25B8%258F%2B2023-09-08%2B15%253A20%253A19%253A%2BHTTPSConnectionPool%2528host%253D%2527api.telegram.org%2527%252C%2Bport%253D443%2529%253A%2BMax%2Bretries%2Bexceeded%2Bwith%2Burl%253A%2B%252Fbot6544001225%253AAAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI%252FsendMessage%253Fchat_id%253D533286897%2526text%253D%2525E2%25259D%252597%2525EF%2525B8%25258F%252B%2525D0%252592%2525D0%2525BE%2525D0%2525B7%2525D0%2525BD%2525D0%2525B8%2525D0%2525BA%2525D0%2525BB%2525D0%2525B0%252B%2525D0%2525BE%2525D1%252588%2525D0%2525B8%2525D0%2525B1%2525D0%2525BA%2525D0%2525B0.%25250A%25250A%252B%2525EF%2525B8%25258F%2525E2%25259D%252597%2525EF%2525B8%25258F%252B2023-09-08%252B15%25253A20%25253A05%25253A%252B%252528%252527Connection%252Baborted.%252527%25252C%252BRemoteDisconnected%252528%252527Remote%252Bend%252Bclosed%252Bconnection%252Bwithout%252Bresponse%252527%252529%252529%25250A%2B%2528Caused%2Bby%2BNameResolutionError%2528%2522%253Curllib3.connection.HTTPSConnection%2Bobject%2Bat%2B0x00000237ABC0DB90%253E%253A%2BFailed%2Bto%2Bresolve%2B%2527api.telegram.org%2527%2B%2528%255BErrno%2B11001%255D%2Bgetaddrinfo%2Bfailed%2529%2522%2529%2529%250A+%28Caused+by+NameResolutionError%28%22%3Curllib3.connection.HTTPSConnection+object+at+0x00000237ABBF2510%3E%3A+Failed+to+resolve+%27api.telegram.org%27+%28%5BErrno+11001%5D+getaddrinfo+failed%29%22%29%29%0A (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000237AC1045D0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-08 15:21:02: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/sendMessage?chat_id=533286897&text=%E2%9D%97%EF%B8%8F+%D0%92%D0%BE%D0%B7%D0%BD%D0%B8%D0%BA%D0%BB%D0%B0+%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D0%B0.%0A%0A+%EF%B8%8F%E2%9D%97%EF%B8%8F+2023-09-08+15%3A20%3A48%3A+HTTPSConnectionPool%28host%3D%27api.telegram.org%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fbot6544001225%3AAAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI%2FsendMessage%3Fchat_id%3D533286897%26text%3D%25E2%259D%2597%25EF%25B8%258F%2B%25D0%2592%25D0%25BE%25D0%25B7%25D0%25BD%25D0%25B8%25D0%25BA%25D0%25BB%25D0%25B0%2B%25D0%25BE%25D1%2588%25D0%25B8%25D0%25B1%25D0%25BA%25D0%25B0.%250A%250A%2B%25EF%25B8%258F%25E2%259D%2597%25EF%25B8%258F%2B2023-09-08%2B15%253A20%253A33%253A%2BHTTPSConnectionPool%2528host%253D%2527api.telegram.org%2527%252C%2Bport%253D443%2529%253A%2BMax%2Bretries%2Bexceeded%2Bwith%2Burl%253A%2B%252Fbot6544001225%253AAAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI%252FsendMessage%253Fchat_id%253D533286897%2526text%253D%2525E2%25259D%252597%2525EF%2525B8%25258F%252B%2525D0%252592%2525D0%2525BE%2525D0%2525B7%2525D0%2525BD%2525D0%2525B8%2525D0%2525BA%2525D0%2525BB%2525D0%2525B0%252B%2525D0%2525BE%2525D1%252588%2525D0%2525B8%2525D0%2525B1%2525D0%2525BA%2525D0%2525B0.%25250A%25250A%252B%2525EF%2525B8%25258F%2525E2%25259D%252597%2525EF%2525B8%25258F%252B2023-09-08%252B15%25253A20%25253A19%25253A%252BHTTPSConnectionPool%252528host%25253D%252527api.telegram.org%252527%25252C%252Bport%25253D443%252529%25253A%252BMax%252Bretries%252Bexceeded%252Bwith%252Burl%25253A%252B%25252Fbot6544001225%25253AAAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI%25252FsendMessage%25253Fchat_id%25253D533286897%252526text%25253D%252525E2%2525259D%25252597%252525EF%252525B8%2525258F%25252B%252525D0%25252592%252525D0%252525BE%252525D0%252525B7%252525D0%252525BD%252525D0%252525B8%252525D0%252525BA%252525D0%252525BB%252525D0%252525B0%25252B%252525D0%252525BE%252525D1%25252588%252525D0%252525B8%252525D0%252525B1%252525D0%252525BA%252525D0%252525B0.%2525250A%2525250A%25252B%252525EF%252525B8%2525258F%252525E2%2525259D%25252597%252525EF%252525B8%2525258F%25252B2023-09-08%25252B15%2525253A20%2525253A05%2525253A%25252B%25252528%25252527Connection%25252Baborted.%25252527%2525252C%25252BRemoteDisconnected%25252528%25252527Remote%25252Bend%25252Bclosed%25252Bconnection%25252Bwithout%25252Bresponse%25252527%25252529%25252529%2525250A%252B%252528Caused%252Bby%252BNameResolutionError%252528%252522%25253Curllib3.connection.HTTPSConnection%252Bobject%252Bat%252B0x00000237ABC0DB90%25253E%25253A%252BFailed%252Bto%252Bresolve%252B%252527api.telegram.org%252527%252B%252528%25255BErrno%252B11001%25255D%252Bgetaddrinfo%252Bfailed%252529%252522%252529%252529%25250A%2B%2528Caused%2Bby%2BNameResolutionError%2528%2522%253Curllib3.connection.HTTPSConnection%2Bobject%2Bat%2B0x00000237ABBF2510%253E%253A%2BFailed%2Bto%2Bresolve%2B%2527api.telegram.org%2527%2B%2528%255BErrno%2B11001%255D%2Bgetaddrinfo%2Bfailed%2529%2522%2529%2529%250A+%28Caused+by+NameResolutionError%28%22%3Curllib3.connection.HTTPSConnection+object+at+0x00000237AC1045D0%3E%3A+Failed+to+resolve+%27api.telegram.org%27+%28%5BErrno+11001%5D+getaddrinfo+failed%29%22%29%29%0A (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000237AC136790>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-08 16:38:38: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=855610772&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000237AAEA71D0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-08 16:38:52: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/sendMessage?chat_id=533286897&text=%E2%9D%97%EF%B8%8F+%D0%92%D0%BE%D0%B7%D0%BD%D0%B8%D0%BA%D0%BB%D0%B0+%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D0%B0.%0A%0A+%EF%B8%8F%E2%9D%97%EF%B8%8F+2023-09-08+16%3A38%3A38%3A+HTTPSConnectionPool%28host%3D%27api.telegram.org%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fbot6544001225%3AAAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI%2FgetUpdates%3Foffset%3D855610772%26timeout%3D20+%28Caused+by+NameResolutionError%28%22%3Curllib3.connection.HTTPSConnection+object+at+0x00000237AAEA71D0%3E%3A+Failed+to+resolve+%27api.telegram.org%27+%28%5BErrno+11001%5D+getaddrinfo+failed%29%22%29%29%0A (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000237ABBF1F10>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-08 16:39:06: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/sendMessage?chat_id=533286897&text=%E2%9D%97%EF%B8%8F+%D0%92%D0%BE%D0%B7%D0%BD%D0%B8%D0%BA%D0%BB%D0%B0+%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D0%B0.%0A%0A+%EF%B8%8F%E2%9D%97%EF%B8%8F+2023-09-08+16%3A38%3A52%3A+HTTPSConnectionPool%28host%3D%27api.telegram.org%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fbot6544001225%3AAAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI%2FsendMessage%3Fchat_id%3D533286897%26text%3D%25E2%259D%2597%25EF%25B8%258F%2B%25D0%2592%25D0%25BE%25D0%25B7%25D0%25BD%25D0%25B8%25D0%25BA%25D0%25BB%25D0%25B0%2B%25D0%25BE%25D1%2588%25D0%25B8%25D0%25B1%25D0%25BA%25D0%25B0.%250A%250A%2B%25EF%25B8%258F%25E2%259D%2597%25EF%25B8%258F%2B2023-09-08%2B16%253A38%253A38%253A%2BHTTPSConnectionPool%2528host%253D%2527api.telegram.org%2527%252C%2Bport%253D443%2529%253A%2BMax%2Bretries%2Bexceeded%2Bwith%2Burl%253A%2B%252Fbot6544001225%253AAAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI%252FgetUpdates%253Foffset%253D855610772%2526timeout%253D20%2B%2528Caused%2Bby%2BNameResolutionError%2528%2522%253Curllib3.connection.HTTPSConnection%2Bobject%2Bat%2B0x00000237AAEA71D0%253E%253A%2BFailed%2Bto%2Bresolve%2B%2527api.telegram.org%2527%2B%2528%255BErrno%2B11001%255D%2Bgetaddrinfo%2Bfailed%2529%2522%2529%2529%250A+%28Caused+by+NameResolutionError%28%22%3Curllib3.connection.HTTPSConnection+object+at+0x00000237ABBF1F10%3E%3A+Failed+to+resolve+%27api.telegram.org%27+%28%5BErrno+11001%5D+getaddrinfo+failed%29%22%29%29%0A (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000237AC104890>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-08 17:26:50: MessageSender.send_message() missing 1 required positional argument: 'cls'
2023-09-08 17:28:21: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/sendPhoto?chat_id=533286897&caption=%F0%9F%92%BC+%3Cb%3E%3Ca+href%3D%22https%3A%2F%2Falmaty.hh.kz%2Fvacancy%2F86453988%3Ffrom%3Dvacancy_search_list%26query%3Dpython%22%3E%D0%93%D0%BB%D0%B0%D0%B2%D0%BD%D1%8B%D0%B9+%D1%81%D0%BF%D0%B5%D1%86%D0%B8%D0%B0%D0%BB%D0%B8%D1%81%D1%82+%28%D1%80%D0%B8%D1%81%D0%BA+%D0%B0%D0%BD%D0%B0%D0%BB%D0%B8%D1%82%D0%B8%D0%BA%29+%D0%94%D0%B5%D0%BF%D0%B0%D1%80%D1%82%D0%B0%D0%BC%D0%B5%D0%BD%D1%82%D0%B0+%D0%B1%D0%B0%D0%BD%D0%BA%D0%BE%D0%B2%D1%81%D0%BA%D0%BE%D0%B9+%D0%B0%D0%BD%D0%B0%D0%BB%D0%B8%D1%82%D0%B8%D0%BA%D0%B8+%D0%B8+%D1%81%D1%82%D1%80%D0%B5%D1%81%D1%81-%D1%82%D0%B5%D1%81%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F%3C%2Fa%3E%3C%2Fb%3E%0A%F0%9F%92%B0+%3Cb%3E%D0%97%D0%B0%D1%80%D0%BF%D0%BB%D0%B0%D1%82%D0%B0+%D0%BD%D0%B5+%D1%83%D0%BA%D0%B0%D0%B7%D0%B0%D0%BD%D0%B0%3C%2Fb%3E%0A%F0%9F%8F%99%EF%B8%8F+%3Cb%3E%D0%A0%D0%93%D0%9F+%D0%90%D0%B3%D0%B5%D0%BD%D1%82%D1%81%D1%82%D0%B2%D0%BE+%D0%A0%D0%B5%D1%81%D0%BF%D1%83%D0%B1%D0%BB%D0%B8%D0%BA%D0%B8+%D0%9A%D0%B0%D0%B7%D0%B0%D1%85%D1%81%D1%82%D0%B0%D0%BD+%D0%BF%D0%BE+%D1%80%D0%B5%D0%B3%D1%83%D0%BB%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8E+%D0%B8+%D1%80%D0%B0%D0%B7%D0%B2%D0%B8%D1%82%D0%B8%D1%8E+%D1%84%D0%B8%D0%BD%D0%B0%D0%BD%D1%81%D0%BE%D0%B2%D0%BE%D0%B3%D0%BE+%D1%80%D1%8B%D0%BD%D0%BA%D0%B0%3C%2Fb%3E%0A&parse_mode=html (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000295F2D6C450>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-08 17:28:36: HTTPSConnectionPool(host='almaty.hh.kz', port=443): Max retries exceeded with url: /search/vacancy?text=python&salary=&no_magic=true&ored_clusters=true&order_by=publication_time&enable_snippets=true&excluded_text=&area=160&page=0 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000295F6BA60D0>: Failed to resolve 'almaty.hh.kz' ([Errno 11001] getaddrinfo failed)"))
2023-09-08 17:44:46: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2023-09-08 17:45:00: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=855610790&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022CDBDF33D0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-08 17:45:16: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=855610790&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022CDBDF2550>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-08 17:46:18: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2023-09-08 17:46:32: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=855610791&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022CDC5C08D0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-08 17:46:48: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=855610791&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022CDA18A8D0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-08 17:51:11: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2023-09-08 17:58:35: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2023-09-08 17:58:49: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=855610796&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028BE7116ED0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-08 17:59:05: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=855610796&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028BE8DBC450>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-08 17:59:19: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=855610796&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028BE7116D10>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-08 18:05:33: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=15)
2023-09-08 18:05:37: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getMe (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000210979A8490>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-08 18:05:41: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getMe (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000210979B8F10>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2023-09-08 18:09:20: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2023-09-08 18:09:34: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6544001225:AAGvMmIurJNpewZzpW7ILIrDFe-7h8QWheI/getUpdates?offset=1&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002BC28C3AF50>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
